"""initial_migration

Revision ID: 609dd7af16b7
Revises: 
Create Date: 2026-06-19 12:16:57.727180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '609dd7af16b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Permissions',
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.Column('PermissionName', sa.String(length=100), nullable=False),
    sa.Column('Module', sa.String(length=50), nullable=False),
    sa.Column('Action', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=200), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('PermissionID'),
    sa.UniqueConstraint('PermissionName')
    )
    op.create_index(op.f('ix_Permissions_PermissionID'), 'Permissions', ['PermissionID'], unique=False)
    op.create_table('Roles',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('RoleName', sa.String(length=50), nullable=False),
    sa.Column('RoleCode', sa.String(length=30), nullable=False),
    sa.Column('Description', sa.String(length=200), nullable=True),
    sa.Column('IsSystem', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('RoleID'),
    sa.UniqueConstraint('RoleCode'),
    sa.UniqueConstraint('RoleName')
    )
    op.create_index(op.f('ix_Roles_RoleID'), 'Roles', ['RoleID'], unique=False)
    op.create_table('SubscriptionPlans',
    sa.Column('PlanID', sa.Integer(), nullable=False),
    sa.Column('PlanName', sa.String(length=100), nullable=False),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('BillingCycle', sa.String(length=20), nullable=False),
    sa.Column('MaxBranches', sa.Integer(), nullable=False),
    sa.Column('MaxStaff', sa.Integer(), nullable=False),
    sa.Column('MaxCustomers', sa.Integer(), nullable=False),
    sa.Column('Features', sa.String(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('PlanID')
    )
    op.create_index(op.f('ix_SubscriptionPlans_PlanID'), 'SubscriptionPlans', ['PlanID'], unique=False)
    op.create_table('RolePermissions',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PermissionID'], ['Permissions.PermissionID'], ),
    sa.ForeignKeyConstraint(['RoleID'], ['Roles.RoleID'], ),
    sa.PrimaryKeyConstraint('RoleID', 'PermissionID')
    )
    op.create_table('Salons',
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('SalonName', sa.String(length=200), nullable=False),
    sa.Column('OwnerName', sa.String(length=200), nullable=True),
    sa.Column('Email', sa.String(length=200), nullable=False),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.String(length=500), nullable=True),
    sa.Column('LogoURL', sa.String(length=500), nullable=True),
    sa.Column('Currency', sa.String(length=10), nullable=False),
    sa.Column('Timezone', sa.String(length=100), nullable=False),
    sa.Column('SubscriptionPlanID', sa.Integer(), nullable=True),
    sa.Column('SubscriptionStatus', sa.String(length=50), nullable=False),
    sa.Column('TrialExpiryDate', sa.DateTime(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('Settings', sa.String(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SubscriptionPlanID'], ['SubscriptionPlans.PlanID'], ),
    sa.PrimaryKeyConstraint('SalonID'),
    sa.UniqueConstraint('Email')
    )
    op.create_index(op.f('ix_Salons_SalonID'), 'Salons', ['SalonID'], unique=False)
    op.create_table('Branches',
    sa.Column('BranchID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('BranchName', sa.String(length=200), nullable=False),
    sa.Column('BranchCode', sa.String(length=20), nullable=True),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=200), nullable=True),
    sa.Column('Address', sa.String(length=500), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('State', sa.String(length=100), nullable=True),
    sa.Column('PostalCode', sa.String(length=20), nullable=True),
    sa.Column('Country', sa.String(length=100), nullable=True),
    sa.Column('Latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('Longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('OpeningTime', sa.Time(), nullable=True),
    sa.Column('ClosingTime', sa.Time(), nullable=True),
    sa.Column('WorkingDays', sa.String(length=100), nullable=True),
    sa.Column('SlotDuration', sa.Integer(), nullable=False),
    sa.Column('MaxAdvanceBookingDays', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('BranchID'),
    sa.UniqueConstraint('BranchCode')
    )
    op.create_index(op.f('ix_Branches_BranchID'), 'Branches', ['BranchID'], unique=False)
    op.create_index(op.f('ix_Branches_SalonID'), 'Branches', ['SalonID'], unique=False)
    op.create_table('Coupons',
    sa.Column('CouponID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('CouponCode', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=200), nullable=True),
    sa.Column('DiscountType', sa.String(length=20), nullable=False),
    sa.Column('DiscountValue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('MinOrderAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('MaxDiscount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('MaxUses', sa.Integer(), nullable=True),
    sa.Column('UsedCount', sa.Integer(), nullable=False),
    sa.Column('ValidFrom', sa.DateTime(), nullable=True),
    sa.Column('ValidUntil', sa.DateTime(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('CouponID')
    )
    op.create_index(op.f('ix_Coupons_CouponCode'), 'Coupons', ['CouponCode'], unique=True)
    op.create_index(op.f('ix_Coupons_CouponID'), 'Coupons', ['CouponID'], unique=False)
    op.create_table('Customers',
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('Gender', sa.String(length=20), nullable=True),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.Column('Mobile', sa.String(length=20), nullable=False),
    sa.Column('Email', sa.String(length=200), nullable=True),
    sa.Column('Address', sa.String(length=500), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('ProfilePictureURL', sa.String(length=500), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.Column('Preferences', sa.String(), nullable=True),
    sa.Column('LoyaltyPoints', sa.Integer(), nullable=False),
    sa.Column('WalletBalance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ReferralCode', sa.String(length=50), nullable=True),
    sa.Column('ReferredByID', sa.Integer(), nullable=True),
    sa.Column('TotalVisits', sa.Integer(), nullable=False),
    sa.Column('TotalSpent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('LastVisitDate', sa.Date(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ReferredByID'], ['Customers.CustomerID'], ),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('CustomerID')
    )
    op.create_index(op.f('ix_Customers_CustomerID'), 'Customers', ['CustomerID'], unique=False)
    op.create_index(op.f('ix_Customers_Email'), 'Customers', ['Email'], unique=False)
    op.create_index(op.f('ix_Customers_Mobile'), 'Customers', ['Mobile'], unique=False)
    op.create_index(op.f('ix_Customers_ReferralCode'), 'Customers', ['ReferralCode'], unique=True)
    op.create_index(op.f('ix_Customers_SalonID'), 'Customers', ['SalonID'], unique=False)
    op.create_table('MembershipPlans',
    sa.Column('PlanID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('PlanName', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('DurationDays', sa.Integer(), nullable=False),
    sa.Column('DiscountPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('LoyaltyBonus', sa.Integer(), nullable=False),
    sa.Column('Benefits', sa.String(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('PlanID')
    )
    op.create_index(op.f('ix_MembershipPlans_PlanID'), 'MembershipPlans', ['PlanID'], unique=False)
    op.create_table('NotificationTemplates',
    sa.Column('TemplateID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=True),
    sa.Column('TemplateName', sa.String(length=200), nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('Event', sa.String(length=100), nullable=True),
    sa.Column('Subject', sa.String(length=500), nullable=True),
    sa.Column('Body', sa.String(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('TemplateID')
    )
    op.create_index(op.f('ix_NotificationTemplates_TemplateID'), 'NotificationTemplates', ['TemplateID'], unique=False)
    op.create_table('Notifications',
    sa.Column('NotificationID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('RecipientType', sa.String(length=50), nullable=False),
    sa.Column('RecipientID', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('Subject', sa.String(length=500), nullable=True),
    sa.Column('Message', sa.String(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('SentAt', sa.DateTime(), nullable=True),
    sa.Column('ErrorMessage', sa.String(length=1000), nullable=True),
    sa.Column('RetryCount', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('NotificationID')
    )
    op.create_index(op.f('ix_Notifications_CreatedAt'), 'Notifications', ['CreatedAt'], unique=False)
    op.create_index(op.f('ix_Notifications_NotificationID'), 'Notifications', ['NotificationID'], unique=False)
    op.create_index(op.f('ix_Notifications_Status'), 'Notifications', ['Status'], unique=False)
    op.create_table('ProductCategories',
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('CategoryName', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('CategoryID')
    )
    op.create_index(op.f('ix_ProductCategories_CategoryID'), 'ProductCategories', ['CategoryID'], unique=False)
    op.create_table('SalonSubscriptions',
    sa.Column('SubscriptionID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('PlanID', sa.Integer(), nullable=False),
    sa.Column('StartDate', sa.Date(), nullable=False),
    sa.Column('EndDate', sa.Date(), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TransactionRef', sa.String(length=200), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['PlanID'], ['SubscriptionPlans.PlanID'], ),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('SubscriptionID')
    )
    op.create_index(op.f('ix_SalonSubscriptions_SubscriptionID'), 'SalonSubscriptions', ['SubscriptionID'], unique=False)
    op.create_table('ServiceCategories',
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('CategoryName', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.Column('IconURL', sa.String(length=500), nullable=True),
    sa.Column('ColorCode', sa.String(length=20), nullable=True),
    sa.Column('SortOrder', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('CategoryID')
    )
    op.create_index(op.f('ix_ServiceCategories_CategoryID'), 'ServiceCategories', ['CategoryID'], unique=False)
    op.create_table('ServicePackages',
    sa.Column('PackageID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('PackageName', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('OriginalPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('PackagePrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ValidityDays', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('PackageID')
    )
    op.create_index(op.f('ix_ServicePackages_PackageID'), 'ServicePackages', ['PackageID'], unique=False)
    op.create_table('Suppliers',
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('SupplierName', sa.String(length=200), nullable=False),
    sa.Column('ContactPerson', sa.String(length=200), nullable=True),
    sa.Column('Email', sa.String(length=200), nullable=True),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.String(length=500), nullable=True),
    sa.Column('GSTIN', sa.String(length=50), nullable=True),
    sa.Column('PaymentTerms', sa.String(length=200), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('SupplierID')
    )
    op.create_index(op.f('ix_Suppliers_SupplierID'), 'Suppliers', ['SupplierID'], unique=False)
    op.create_table('CustomerAuth',
    sa.Column('AuthID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('IsEmailVerified', sa.Boolean(), nullable=False),
    sa.Column('OTPCode', sa.String(length=10), nullable=True),
    sa.Column('OTPExpiry', sa.DateTime(), nullable=True),
    sa.Column('LastLoginAt', sa.DateTime(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.PrimaryKeyConstraint('AuthID'),
    sa.UniqueConstraint('CustomerID')
    )
    op.create_index(op.f('ix_CustomerAuth_AuthID'), 'CustomerAuth', ['AuthID'], unique=False)
    op.create_table('CustomerMemberships',
    sa.Column('MembershipID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('PlanID', sa.Integer(), nullable=False),
    sa.Column('StartDate', sa.Date(), nullable=False),
    sa.Column('EndDate', sa.Date(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.ForeignKeyConstraint(['PlanID'], ['MembershipPlans.PlanID'], ),
    sa.PrimaryKeyConstraint('MembershipID')
    )
    op.create_index(op.f('ix_CustomerMemberships_MembershipID'), 'CustomerMemberships', ['MembershipID'], unique=False)
    op.create_table('CustomerReviews',
    sa.Column('ReviewID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('BranchID', sa.Integer(), nullable=False),
    sa.Column('AppointmentID', sa.Integer(), nullable=True),
    sa.Column('StaffID', sa.Integer(), nullable=True),
    sa.Column('Rating', sa.Integer(), nullable=False),
    sa.Column('Review', sa.String(), nullable=True),
    sa.Column('IsPublic', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BranchID'], ['Branches.BranchID'], ),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.PrimaryKeyConstraint('ReviewID')
    )
    op.create_index(op.f('ix_CustomerReviews_ReviewID'), 'CustomerReviews', ['ReviewID'], unique=False)
    op.create_table('LoyaltyTransactions',
    sa.Column('TransactionID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('InvoiceID', sa.Integer(), nullable=True),
    sa.Column('Points', sa.Integer(), nullable=False),
    sa.Column('TransactionType', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.Column('BalanceAfter', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.PrimaryKeyConstraint('TransactionID')
    )
    op.create_index(op.f('ix_LoyaltyTransactions_TransactionID'), 'LoyaltyTransactions', ['TransactionID'], unique=False)
    op.create_table('Products',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.Column('SupplierID', sa.Integer(), nullable=True),
    sa.Column('ProductName', sa.String(length=200), nullable=False),
    sa.Column('SKU', sa.String(length=100), nullable=True),
    sa.Column('Barcode', sa.String(length=100), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('CostPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('SalePrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TaxPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('Unit', sa.String(length=50), nullable=True),
    sa.Column('HSNCode', sa.String(length=20), nullable=True),
    sa.Column('ImageURL', sa.String(length=500), nullable=True),
    sa.Column('IsForSale', sa.Boolean(), nullable=False),
    sa.Column('IsForUse', sa.Boolean(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CategoryID'], ['ProductCategories.CategoryID'], ),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.ForeignKeyConstraint(['SupplierID'], ['Suppliers.SupplierID'], ),
    sa.PrimaryKeyConstraint('ProductID'),
    sa.UniqueConstraint('SKU')
    )
    op.create_index(op.f('ix_Products_ProductID'), 'Products', ['ProductID'], unique=False)
    op.create_table('Services',
    sa.Column('ServiceID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.Column('ServiceName', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Duration', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TaxPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('GenderType', sa.String(length=20), nullable=False),
    sa.Column('ImageURL', sa.String(length=500), nullable=True),
    sa.Column('ColorCode', sa.String(length=20), nullable=True),
    sa.Column('SortOrder', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CategoryID'], ['ServiceCategories.CategoryID'], ),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('ServiceID')
    )
    op.create_index(op.f('ix_Services_SalonID'), 'Services', ['SalonID'], unique=False)
    op.create_index(op.f('ix_Services_ServiceID'), 'Services', ['ServiceID'], unique=False)
    op.create_table('Users',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=True),
    sa.Column('BranchID', sa.Integer(), nullable=True),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=200), nullable=False),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('ProfilePictureURL', sa.String(length=500), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('IsEmailVerified', sa.Boolean(), nullable=False),
    sa.Column('EmailVerificationToken', sa.String(length=255), nullable=True),
    sa.Column('EmailTokenExpiry', sa.DateTime(), nullable=True),
    sa.Column('ResetPasswordToken', sa.String(length=255), nullable=True),
    sa.Column('ResetPasswordExpiry', sa.DateTime(), nullable=True),
    sa.Column('OTPCode', sa.String(length=10), nullable=True),
    sa.Column('OTPExpiry', sa.DateTime(), nullable=True),
    sa.Column('LastLoginAt', sa.DateTime(), nullable=True),
    sa.Column('FailedLoginAttempts', sa.Integer(), nullable=False),
    sa.Column('LockedUntil', sa.DateTime(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BranchID'], ['Branches.BranchID'], ),
    sa.ForeignKeyConstraint(['RoleID'], ['Roles.RoleID'], ),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_index(op.f('ix_Users_BranchID'), 'Users', ['BranchID'], unique=False)
    op.create_index(op.f('ix_Users_Email'), 'Users', ['Email'], unique=True)
    op.create_index(op.f('ix_Users_SalonID'), 'Users', ['SalonID'], unique=False)
    op.create_index(op.f('ix_Users_UserID'), 'Users', ['UserID'], unique=False)
    op.create_table('WalletTransactions',
    sa.Column('TransactionID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TransactionType', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.Column('BalanceAfter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('InvoiceID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.PrimaryKeyConstraint('TransactionID')
    )
    op.create_index(op.f('ix_WalletTransactions_TransactionID'), 'WalletTransactions', ['TransactionID'], unique=False)
    op.create_table('Campaigns',
    sa.Column('CampaignID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('CampaignName', sa.String(length=200), nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('Subject', sa.String(length=500), nullable=True),
    sa.Column('Message', sa.String(), nullable=False),
    sa.Column('TargetAudience', sa.String(length=100), nullable=False),
    sa.Column('FiltersJSON', sa.String(), nullable=True),
    sa.Column('ScheduledAt', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('TotalRecipients', sa.Integer(), nullable=False),
    sa.Column('SentCount', sa.Integer(), nullable=False),
    sa.Column('FailedCount', sa.Integer(), nullable=False),
    sa.Column('CreatedByUserID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CreatedByUserID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('CampaignID')
    )
    op.create_index(op.f('ix_Campaigns_CampaignID'), 'Campaigns', ['CampaignID'], unique=False)
    op.create_table('Inventory',
    sa.Column('InventoryID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('BranchID', sa.Integer(), nullable=False),
    sa.Column('CurrentStock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('MinStockLevel', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('MaxStockLevel', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ReorderPoint', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('LastRestockedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BranchID'], ['Branches.BranchID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.PrimaryKeyConstraint('InventoryID')
    )
    op.create_index(op.f('ix_Inventory_InventoryID'), 'Inventory', ['InventoryID'], unique=False)
    op.create_table('PackageServices',
    sa.Column('PackageID', sa.Integer(), nullable=False),
    sa.Column('ServiceID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PackageID'], ['ServicePackages.PackageID'], ),
    sa.ForeignKeyConstraint(['ServiceID'], ['Services.ServiceID'], ),
    sa.PrimaryKeyConstraint('PackageID', 'ServiceID')
    )
    op.create_table('PurchaseOrders',
    sa.Column('POID', sa.Integer(), nullable=False),
    sa.Column('PONumber', sa.String(length=50), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('BranchID', sa.Integer(), nullable=False),
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('OrderDate', sa.Date(), nullable=False),
    sa.Column('ExpectedDate', sa.Date(), nullable=True),
    sa.Column('ReceivedDate', sa.Date(), nullable=True),
    sa.Column('SubTotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TaxAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TotalAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.Column('CreatedByUserID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BranchID'], ['Branches.BranchID'], ),
    sa.ForeignKeyConstraint(['CreatedByUserID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.ForeignKeyConstraint(['SupplierID'], ['Suppliers.SupplierID'], ),
    sa.PrimaryKeyConstraint('POID'),
    sa.UniqueConstraint('PONumber')
    )
    op.create_index(op.f('ix_PurchaseOrders_POID'), 'PurchaseOrders', ['POID'], unique=False)
    op.create_table('RefreshTokens',
    sa.Column('TokenID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Token', sa.String(length=500), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(), nullable=False),
    sa.Column('IsRevoked', sa.Boolean(), nullable=False),
    sa.Column('DeviceInfo', sa.String(length=500), nullable=True),
    sa.Column('IPAddress', sa.String(length=50), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('TokenID')
    )
    op.create_index(op.f('ix_RefreshTokens_TokenID'), 'RefreshTokens', ['TokenID'], unique=False)
    op.create_table('ServiceAddons',
    sa.Column('AddonID', sa.Integer(), nullable=False),
    sa.Column('ServiceID', sa.Integer(), nullable=False),
    sa.Column('AddonName', sa.String(length=200), nullable=False),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Duration', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ServiceID'], ['Services.ServiceID'], ),
    sa.PrimaryKeyConstraint('AddonID')
    )
    op.create_index(op.f('ix_ServiceAddons_AddonID'), 'ServiceAddons', ['AddonID'], unique=False)
    op.create_table('Staff',
    sa.Column('StaffID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('BranchID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('StaffCode', sa.String(length=50), nullable=True),
    sa.Column('JobTitle', sa.String(length=100), nullable=True),
    sa.Column('Skills', sa.String(), nullable=True),
    sa.Column('Experience', sa.Integer(), nullable=False),
    sa.Column('Salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('CommissionPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('JoiningDate', sa.Date(), nullable=True),
    sa.Column('Gender', sa.String(length=20), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('TotalServiced', sa.Integer(), nullable=False),
    sa.Column('AverageRating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BranchID'], ['Branches.BranchID'], ),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('StaffID'),
    sa.UniqueConstraint('StaffCode'),
    sa.UniqueConstraint('UserID')
    )
    op.create_index(op.f('ix_Staff_BranchID'), 'Staff', ['BranchID'], unique=False)
    op.create_index(op.f('ix_Staff_SalonID'), 'Staff', ['SalonID'], unique=False)
    op.create_index(op.f('ix_Staff_StaffID'), 'Staff', ['StaffID'], unique=False)
    op.create_table('Appointments',
    sa.Column('AppointmentID', sa.Integer(), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('BranchID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('StaffID', sa.Integer(), nullable=True),
    sa.Column('ServiceID', sa.Integer(), nullable=False),
    sa.Column('AppointmentDate', sa.Date(), nullable=False),
    sa.Column('StartTime', sa.Time(), nullable=False),
    sa.Column('EndTime', sa.Time(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.Column('CancellationReason', sa.String(length=500), nullable=True),
    sa.Column('RescheduledFromID', sa.Integer(), nullable=True),
    sa.Column('BookingSource', sa.String(length=50), nullable=False),
    sa.Column('ServiceAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ReminderSent', sa.Boolean(), nullable=False),
    sa.Column('Reminder24hSent', sa.Boolean(), nullable=False),
    sa.Column('Reminder1hSent', sa.Boolean(), nullable=False),
    sa.Column('CreatedByUserID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BranchID'], ['Branches.BranchID'], ),
    sa.ForeignKeyConstraint(['CreatedByUserID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.ForeignKeyConstraint(['RescheduledFromID'], ['Appointments.AppointmentID'], ),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.ForeignKeyConstraint(['ServiceID'], ['Services.ServiceID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['Staff.StaffID'], ),
    sa.PrimaryKeyConstraint('AppointmentID')
    )
    op.create_index(op.f('ix_Appointments_AppointmentDate'), 'Appointments', ['AppointmentDate'], unique=False)
    op.create_index(op.f('ix_Appointments_AppointmentID'), 'Appointments', ['AppointmentID'], unique=False)
    op.create_index(op.f('ix_Appointments_BranchID'), 'Appointments', ['BranchID'], unique=False)
    op.create_index(op.f('ix_Appointments_CustomerID'), 'Appointments', ['CustomerID'], unique=False)
    op.create_index(op.f('ix_Appointments_StaffID'), 'Appointments', ['StaffID'], unique=False)
    op.create_index(op.f('ix_Appointments_Status'), 'Appointments', ['Status'], unique=False)
    op.create_table('Commissions',
    sa.Column('CommissionID', sa.Integer(), nullable=False),
    sa.Column('StaffID', sa.Integer(), nullable=False),
    sa.Column('InvoiceID', sa.Integer(), nullable=False),
    sa.Column('InvoiceItemID', sa.Integer(), nullable=True),
    sa.Column('BaseAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('CommissionPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('PayrollID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['StaffID'], ['Staff.StaffID'], ),
    sa.PrimaryKeyConstraint('CommissionID')
    )
    op.create_index(op.f('ix_Commissions_CommissionID'), 'Commissions', ['CommissionID'], unique=False)
    op.create_table('Leaves',
    sa.Column('LeaveID', sa.Integer(), nullable=False),
    sa.Column('StaffID', sa.Integer(), nullable=False),
    sa.Column('LeaveType', sa.String(length=50), nullable=False),
    sa.Column('FromDate', sa.Date(), nullable=False),
    sa.Column('ToDate', sa.Date(), nullable=False),
    sa.Column('TotalDays', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('Reason', sa.String(length=500), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('ApprovedByUserID', sa.Integer(), nullable=True),
    sa.Column('ApprovedAt', sa.DateTime(), nullable=True),
    sa.Column('RejectionReason', sa.String(length=500), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ApprovedByUserID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['Staff.StaffID'], ),
    sa.PrimaryKeyConstraint('LeaveID')
    )
    op.create_index(op.f('ix_Leaves_LeaveID'), 'Leaves', ['LeaveID'], unique=False)
    op.create_table('Payroll',
    sa.Column('PayrollID', sa.Integer(), nullable=False),
    sa.Column('StaffID', sa.Integer(), nullable=False),
    sa.Column('PayPeriodStart', sa.Date(), nullable=False),
    sa.Column('PayPeriodEnd', sa.Date(), nullable=False),
    sa.Column('BaseSalary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TotalCommission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TotalDeductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('NetPay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('WorkingDays', sa.Integer(), nullable=True),
    sa.Column('PresentDays', sa.Integer(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('ProcessedByUserID', sa.Integer(), nullable=True),
    sa.Column('ProcessedAt', sa.DateTime(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ProcessedByUserID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['Staff.StaffID'], ),
    sa.PrimaryKeyConstraint('PayrollID')
    )
    op.create_index(op.f('ix_Payroll_PayrollID'), 'Payroll', ['PayrollID'], unique=False)
    op.create_table('PurchaseOrderItems',
    sa.Column('ItemID', sa.Integer(), nullable=False),
    sa.Column('POID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('OrderedQuantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ReceivedQuantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TaxPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('TotalPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['POID'], ['PurchaseOrders.POID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.PrimaryKeyConstraint('ItemID')
    )
    op.create_index(op.f('ix_PurchaseOrderItems_ItemID'), 'PurchaseOrderItems', ['ItemID'], unique=False)
    op.create_table('StaffAttendance',
    sa.Column('AttendanceID', sa.Integer(), nullable=False),
    sa.Column('StaffID', sa.Integer(), nullable=False),
    sa.Column('AttendanceDate', sa.Date(), nullable=False),
    sa.Column('CheckInTime', sa.DateTime(), nullable=True),
    sa.Column('CheckOutTime', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Notes', sa.String(length=500), nullable=True),
    sa.Column('MarkedByUserID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MarkedByUserID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['Staff.StaffID'], ),
    sa.PrimaryKeyConstraint('AttendanceID')
    )
    op.create_index(op.f('ix_StaffAttendance_AttendanceID'), 'StaffAttendance', ['AttendanceID'], unique=False)
    op.create_table('StaffSchedules',
    sa.Column('ScheduleID', sa.Integer(), nullable=False),
    sa.Column('StaffID', sa.Integer(), nullable=False),
    sa.Column('DayOfWeek', sa.Integer(), nullable=False),
    sa.Column('StartTime', sa.Time(), nullable=False),
    sa.Column('EndTime', sa.Time(), nullable=False),
    sa.Column('IsWorking', sa.Boolean(), nullable=False),
    sa.Column('BreakStart', sa.Time(), nullable=True),
    sa.Column('BreakEnd', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['StaffID'], ['Staff.StaffID'], ),
    sa.PrimaryKeyConstraint('ScheduleID')
    )
    op.create_index(op.f('ix_StaffSchedules_ScheduleID'), 'StaffSchedules', ['ScheduleID'], unique=False)
    op.create_table('StaffServices',
    sa.Column('StaffID', sa.Integer(), nullable=False),
    sa.Column('ServiceID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ServiceID'], ['Services.ServiceID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['Staff.StaffID'], ),
    sa.PrimaryKeyConstraint('StaffID', 'ServiceID')
    )
    op.create_table('Waitlist',
    sa.Column('WaitlistID', sa.Integer(), nullable=False),
    sa.Column('BranchID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('ServiceID', sa.Integer(), nullable=False),
    sa.Column('StaffID', sa.Integer(), nullable=True),
    sa.Column('PreferredDate', sa.Date(), nullable=True),
    sa.Column('PreferredTime', sa.Time(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Notes', sa.String(length=500), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BranchID'], ['Branches.BranchID'], ),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.ForeignKeyConstraint(['ServiceID'], ['Services.ServiceID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['Staff.StaffID'], ),
    sa.PrimaryKeyConstraint('WaitlistID')
    )
    op.create_index(op.f('ix_Waitlist_WaitlistID'), 'Waitlist', ['WaitlistID'], unique=False)
    op.create_table('AppointmentAddons',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('AppointmentID', sa.Integer(), nullable=False),
    sa.Column('AddonID', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['AddonID'], ['ServiceAddons.AddonID'], ),
    sa.ForeignKeyConstraint(['AppointmentID'], ['Appointments.AppointmentID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_AppointmentAddons_ID'), 'AppointmentAddons', ['ID'], unique=False)
    op.create_table('CheckIns',
    sa.Column('CheckInID', sa.Integer(), nullable=False),
    sa.Column('BranchID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('AppointmentID', sa.Integer(), nullable=True),
    sa.Column('StaffID', sa.Integer(), nullable=True),
    sa.Column('ServiceID', sa.Integer(), nullable=False),
    sa.Column('QueueNumber', sa.Integer(), nullable=True),
    sa.Column('CheckInTime', sa.DateTime(), nullable=False),
    sa.Column('StartServiceTime', sa.DateTime(), nullable=True),
    sa.Column('EndServiceTime', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Notes', sa.String(length=500), nullable=True),
    sa.Column('CreatedByUserID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AppointmentID'], ['Appointments.AppointmentID'], ),
    sa.ForeignKeyConstraint(['BranchID'], ['Branches.BranchID'], ),
    sa.ForeignKeyConstraint(['CreatedByUserID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.ForeignKeyConstraint(['ServiceID'], ['Services.ServiceID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['Staff.StaffID'], ),
    sa.PrimaryKeyConstraint('CheckInID')
    )
    op.create_index(op.f('ix_CheckIns_BranchID'), 'CheckIns', ['BranchID'], unique=False)
    op.create_index(op.f('ix_CheckIns_CheckInID'), 'CheckIns', ['CheckInID'], unique=False)
    op.create_index(op.f('ix_CheckIns_StaffID'), 'CheckIns', ['StaffID'], unique=False)
    op.create_index(op.f('ix_CheckIns_Status'), 'CheckIns', ['Status'], unique=False)
    op.create_table('Invoices',
    sa.Column('InvoiceID', sa.Integer(), nullable=False),
    sa.Column('InvoiceNumber', sa.String(length=50), nullable=False),
    sa.Column('SalonID', sa.Integer(), nullable=False),
    sa.Column('BranchID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('AppointmentID', sa.Integer(), nullable=True),
    sa.Column('CheckInID', sa.Integer(), nullable=True),
    sa.Column('SubTotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TaxAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('DiscountAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('CouponID', sa.Integer(), nullable=True),
    sa.Column('WalletUsed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('LoyaltyUsed', sa.Integer(), nullable=False),
    sa.Column('TotalAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('PaidAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('BalanceAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Notes', sa.String(length=500), nullable=True),
    sa.Column('PrintedCount', sa.Integer(), nullable=False),
    sa.Column('CreatedByUserID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AppointmentID'], ['Appointments.AppointmentID'], ),
    sa.ForeignKeyConstraint(['BranchID'], ['Branches.BranchID'], ),
    sa.ForeignKeyConstraint(['CheckInID'], ['CheckIns.CheckInID'], ),
    sa.ForeignKeyConstraint(['CouponID'], ['Coupons.CouponID'], ),
    sa.ForeignKeyConstraint(['CreatedByUserID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.ForeignKeyConstraint(['SalonID'], ['Salons.SalonID'], ),
    sa.PrimaryKeyConstraint('InvoiceID')
    )
    op.create_index(op.f('ix_Invoices_BranchID'), 'Invoices', ['BranchID'], unique=False)
    op.create_index(op.f('ix_Invoices_CreatedAt'), 'Invoices', ['CreatedAt'], unique=False)
    op.create_index(op.f('ix_Invoices_CustomerID'), 'Invoices', ['CustomerID'], unique=False)
    op.create_index(op.f('ix_Invoices_InvoiceID'), 'Invoices', ['InvoiceID'], unique=False)
    op.create_index(op.f('ix_Invoices_InvoiceNumber'), 'Invoices', ['InvoiceNumber'], unique=True)
    op.create_index(op.f('ix_Invoices_Status'), 'Invoices', ['Status'], unique=False)
    op.create_table('InvoiceItems',
    sa.Column('ItemID', sa.Integer(), nullable=False),
    sa.Column('InvoiceID', sa.Integer(), nullable=False),
    sa.Column('ItemType', sa.String(length=50), nullable=False),
    sa.Column('ItemRefID', sa.Integer(), nullable=True),
    sa.Column('ItemName', sa.String(length=200), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TaxPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('TaxAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('DiscountPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('DiscountAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TotalPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('StaffID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['InvoiceID'], ['Invoices.InvoiceID'], ),
    sa.ForeignKeyConstraint(['StaffID'], ['Staff.StaffID'], ),
    sa.PrimaryKeyConstraint('ItemID')
    )
    op.create_index(op.f('ix_InvoiceItems_ItemID'), 'InvoiceItems', ['ItemID'], unique=False)
    op.create_table('Payments',
    sa.Column('PaymentID', sa.Integer(), nullable=False),
    sa.Column('InvoiceID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('PaymentMethod', sa.String(length=50), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TransactionID', sa.String(length=200), nullable=True),
    sa.Column('GatewayResponse', sa.String(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Notes', sa.String(length=500), nullable=True),
    sa.Column('RefundedAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('RefundedAt', sa.DateTime(), nullable=True),
    sa.Column('CreatedByUserID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CreatedByUserID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.ForeignKeyConstraint(['InvoiceID'], ['Invoices.InvoiceID'], ),
    sa.PrimaryKeyConstraint('PaymentID')
    )
    op.create_index(op.f('ix_Payments_PaymentID'), 'Payments', ['PaymentID'], unique=False)
    op.create_table('StockTransactions',
    sa.Column('TransactionID', sa.Integer(), nullable=False),
    sa.Column('InventoryID', sa.Integer(), nullable=False),
    sa.Column('TransactionType', sa.String(length=50), nullable=False),
    sa.Column('Quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('BalanceBefore', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('BalanceAfter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Notes', sa.String(length=500), nullable=True),
    sa.Column('POID', sa.Integer(), nullable=True),
    sa.Column('InvoiceID', sa.Integer(), nullable=True),
    sa.Column('CreatedByUserID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CreatedByUserID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['InventoryID'], ['Inventory.InventoryID'], ),
    sa.ForeignKeyConstraint(['InvoiceID'], ['Invoices.InvoiceID'], ),
    sa.ForeignKeyConstraint(['POID'], ['PurchaseOrders.POID'], ),
    sa.PrimaryKeyConstraint('TransactionID')
    )
    op.create_index(op.f('ix_StockTransactions_TransactionID'), 'StockTransactions', ['TransactionID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_StockTransactions_TransactionID'), table_name='StockTransactions')
    op.drop_table('StockTransactions')
    op.drop_index(op.f('ix_Payments_PaymentID'), table_name='Payments')
    op.drop_table('Payments')
    op.drop_index(op.f('ix_InvoiceItems_ItemID'), table_name='InvoiceItems')
    op.drop_table('InvoiceItems')
    op.drop_index(op.f('ix_Invoices_Status'), table_name='Invoices')
    op.drop_index(op.f('ix_Invoices_InvoiceNumber'), table_name='Invoices')
    op.drop_index(op.f('ix_Invoices_InvoiceID'), table_name='Invoices')
    op.drop_index(op.f('ix_Invoices_CustomerID'), table_name='Invoices')
    op.drop_index(op.f('ix_Invoices_CreatedAt'), table_name='Invoices')
    op.drop_index(op.f('ix_Invoices_BranchID'), table_name='Invoices')
    op.drop_table('Invoices')
    op.drop_index(op.f('ix_CheckIns_Status'), table_name='CheckIns')
    op.drop_index(op.f('ix_CheckIns_StaffID'), table_name='CheckIns')
    op.drop_index(op.f('ix_CheckIns_CheckInID'), table_name='CheckIns')
    op.drop_index(op.f('ix_CheckIns_BranchID'), table_name='CheckIns')
    op.drop_table('CheckIns')
    op.drop_index(op.f('ix_AppointmentAddons_ID'), table_name='AppointmentAddons')
    op.drop_table('AppointmentAddons')
    op.drop_index(op.f('ix_Waitlist_WaitlistID'), table_name='Waitlist')
    op.drop_table('Waitlist')
    op.drop_table('StaffServices')
    op.drop_index(op.f('ix_StaffSchedules_ScheduleID'), table_name='StaffSchedules')
    op.drop_table('StaffSchedules')
    op.drop_index(op.f('ix_StaffAttendance_AttendanceID'), table_name='StaffAttendance')
    op.drop_table('StaffAttendance')
    op.drop_index(op.f('ix_PurchaseOrderItems_ItemID'), table_name='PurchaseOrderItems')
    op.drop_table('PurchaseOrderItems')
    op.drop_index(op.f('ix_Payroll_PayrollID'), table_name='Payroll')
    op.drop_table('Payroll')
    op.drop_index(op.f('ix_Leaves_LeaveID'), table_name='Leaves')
    op.drop_table('Leaves')
    op.drop_index(op.f('ix_Commissions_CommissionID'), table_name='Commissions')
    op.drop_table('Commissions')
    op.drop_index(op.f('ix_Appointments_Status'), table_name='Appointments')
    op.drop_index(op.f('ix_Appointments_StaffID'), table_name='Appointments')
    op.drop_index(op.f('ix_Appointments_CustomerID'), table_name='Appointments')
    op.drop_index(op.f('ix_Appointments_BranchID'), table_name='Appointments')
    op.drop_index(op.f('ix_Appointments_AppointmentID'), table_name='Appointments')
    op.drop_index(op.f('ix_Appointments_AppointmentDate'), table_name='Appointments')
    op.drop_table('Appointments')
    op.drop_index(op.f('ix_Staff_StaffID'), table_name='Staff')
    op.drop_index(op.f('ix_Staff_SalonID'), table_name='Staff')
    op.drop_index(op.f('ix_Staff_BranchID'), table_name='Staff')
    op.drop_table('Staff')
    op.drop_index(op.f('ix_ServiceAddons_AddonID'), table_name='ServiceAddons')
    op.drop_table('ServiceAddons')
    op.drop_index(op.f('ix_RefreshTokens_TokenID'), table_name='RefreshTokens')
    op.drop_table('RefreshTokens')
    op.drop_index(op.f('ix_PurchaseOrders_POID'), table_name='PurchaseOrders')
    op.drop_table('PurchaseOrders')
    op.drop_table('PackageServices')
    op.drop_index(op.f('ix_Inventory_InventoryID'), table_name='Inventory')
    op.drop_table('Inventory')
    op.drop_index(op.f('ix_Campaigns_CampaignID'), table_name='Campaigns')
    op.drop_table('Campaigns')
    op.drop_index(op.f('ix_WalletTransactions_TransactionID'), table_name='WalletTransactions')
    op.drop_table('WalletTransactions')
    op.drop_index(op.f('ix_Users_UserID'), table_name='Users')
    op.drop_index(op.f('ix_Users_SalonID'), table_name='Users')
    op.drop_index(op.f('ix_Users_Email'), table_name='Users')
    op.drop_index(op.f('ix_Users_BranchID'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Services_ServiceID'), table_name='Services')
    op.drop_index(op.f('ix_Services_SalonID'), table_name='Services')
    op.drop_table('Services')
    op.drop_index(op.f('ix_Products_ProductID'), table_name='Products')
    op.drop_table('Products')
    op.drop_index(op.f('ix_LoyaltyTransactions_TransactionID'), table_name='LoyaltyTransactions')
    op.drop_table('LoyaltyTransactions')
    op.drop_index(op.f('ix_CustomerReviews_ReviewID'), table_name='CustomerReviews')
    op.drop_table('CustomerReviews')
    op.drop_index(op.f('ix_CustomerMemberships_MembershipID'), table_name='CustomerMemberships')
    op.drop_table('CustomerMemberships')
    op.drop_index(op.f('ix_CustomerAuth_AuthID'), table_name='CustomerAuth')
    op.drop_table('CustomerAuth')
    op.drop_index(op.f('ix_Suppliers_SupplierID'), table_name='Suppliers')
    op.drop_table('Suppliers')
    op.drop_index(op.f('ix_ServicePackages_PackageID'), table_name='ServicePackages')
    op.drop_table('ServicePackages')
    op.drop_index(op.f('ix_ServiceCategories_CategoryID'), table_name='ServiceCategories')
    op.drop_table('ServiceCategories')
    op.drop_index(op.f('ix_SalonSubscriptions_SubscriptionID'), table_name='SalonSubscriptions')
    op.drop_table('SalonSubscriptions')
    op.drop_index(op.f('ix_ProductCategories_CategoryID'), table_name='ProductCategories')
    op.drop_table('ProductCategories')
    op.drop_index(op.f('ix_Notifications_Status'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_NotificationID'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_CreatedAt'), table_name='Notifications')
    op.drop_table('Notifications')
    op.drop_index(op.f('ix_NotificationTemplates_TemplateID'), table_name='NotificationTemplates')
    op.drop_table('NotificationTemplates')
    op.drop_index(op.f('ix_MembershipPlans_PlanID'), table_name='MembershipPlans')
    op.drop_table('MembershipPlans')
    op.drop_index(op.f('ix_Customers_SalonID'), table_name='Customers')
    op.drop_index(op.f('ix_Customers_ReferralCode'), table_name='Customers')
    op.drop_index(op.f('ix_Customers_Mobile'), table_name='Customers')
    op.drop_index(op.f('ix_Customers_Email'), table_name='Customers')
    op.drop_index(op.f('ix_Customers_CustomerID'), table_name='Customers')
    op.drop_table('Customers')
    op.drop_index(op.f('ix_Coupons_CouponID'), table_name='Coupons')
    op.drop_index(op.f('ix_Coupons_CouponCode'), table_name='Coupons')
    op.drop_table('Coupons')
    op.drop_index(op.f('ix_Branches_SalonID'), table_name='Branches')
    op.drop_index(op.f('ix_Branches_BranchID'), table_name='Branches')
    op.drop_table('Branches')
    op.drop_index(op.f('ix_Salons_SalonID'), table_name='Salons')
    op.drop_table('Salons')
    op.drop_table('RolePermissions')
    op.drop_index(op.f('ix_SubscriptionPlans_PlanID'), table_name='SubscriptionPlans')
    op.drop_table('SubscriptionPlans')
    op.drop_index(op.f('ix_Roles_RoleID'), table_name='Roles')
    op.drop_table('Roles')
    op.drop_index(op.f('ix_Permissions_PermissionID'), table_name='Permissions')
    op.drop_table('Permissions')
    # ### end Alembic commands ###
